# 数据集下载链接
rar_file: 'http://vcl.ucsd.edu/hed/HED-BSDS.tar'
# 数据集本地下载的目录
download_path: 'hed-data'
# 本地model相关参数和Graph的保存目录
save_dir: 'save_dir'
# 本地测试结果保存目录
test_output: 'test_output'
# 现有的model文件
model_weights_path: 'vgg16.npy'
# training batch size, 取决于GPU
batch_size_train: 10
# validation batch size, ran every val_interval
batch_size_val: 10
# 训练集取总数的占比
train_split: 0.8
# 训练多少次
max_iterations: 100000
# optimizer params (not used currently Adam is used by default)
optimizer: 'adam'
optimizer_params:
    learning_rate: 0.001
    weight_decay: 0.0002
# Section 4.1 Loss for layer fusion
loss_weights: 1.0
# save snapshot every save_interval iterations
save_interval: 100
# validate on held out dataset
val_interval: 10
# learning rate decay (Not used with Adam currently)
learning_rate_decay: 0.1
# Apply weighted_cross_entropy_loss to outputs from each side layer
# Setting to false only loss after last conv layer is computed
deep_supervision: True
# Targets are continue if True else binary {0, 1}
target_regression: True
# Mean pixel value to subtract from BGR image
mean_pixel_value: [103.939, 116.779, 123.68]
# RGB to BGR (VGG-16 trained with BGR blame OpenCV)
channel_swap: [2, 1, 0]
# training/validation data
training:
    dir: HED-BSDS
    list: HED-BSDS/train_pair.lst
    #
    image_width: 224
    image_height: 224
    n_channels: 3
# testing data
testing:
    dir: HED-BSDS
    list: HED-BSDS/test.lst
    #
    image_width: 224
    image_height: 224
    n_channels: 3
# use snapshot after test_snapshot intervals for testing
test_snapshot: 800
# Apply testing_threshold after sigmoid to generate binary maps set to 0.0 for continous valued edge maps
testing_threshold: 0.0